// Comprehensive data for all 82 provinces of the Philippines
export const provinceData = {
  "Abra": {
    status: "available",
    price: 200,
    athletes: [],
    population: "250,985",
    capital: "Bangued",
    region: "Cordillera Administrative Region (CAR)",
    area: "4,199.72 km²",
    density: "60 per km²",
    cities: 0,
    municipalities: 27,
    barangays: 303,
    description: "Known for its rich cultural heritage and the Kalingas' traditional practices. Famous for its woven products and scenic mountain landscapes.",
    attractions: ["Kaparkan Falls", "Mount Pulag", "Abra River", "Traditional Weaving Centers"],
    economy: "Agriculture, handicrafts, mining",
    languages: ["Ilocano", "Tingguian", "Tagalog"]
  },
  "Agusan del Norte": {
    status: "available",
    price: 220,
    athletes: [],
    population: "387,503",
    capital: "Cabadbaran",
    region: "Caraga (Region XIII)",
    area: "2,611.63 km²",
    density: "148 per km²",
    cities: 1,
    municipalities: 10,
    barangays: 167,
    description: "Gateway to Caraga region, known for its rich biodiversity and the Agusan River. Major logging and mining area.",
    attractions: ["Agusan River", "Magallanes Eco-Tourism Park", "Lake Mainit", "Cabadbaran Cathedral"],
    economy: "Logging, mining, agriculture, fishing",
    languages: ["Cebuano", "Surigaonon", "Tagalog"]
  },
  "Agusan del Sur": {
    status: "available",
    price: 250,
    athletes: [],
    population: "739,367",
    capital: "Prosperidad",
    region: "Caraga (Region XIII)",
    area: "9,989.52 km²",
    density: "74 per km²",
    cities: 1,
    municipalities: 13,
    barangays: 314,
    description: "Home to the Agusan Marsh Wildlife Sanctuary, one of the most important wetland areas in the Philippines.",
    attractions: ["Agusan Marsh Wildlife Sanctuary", "Bunawan Eco-Park", "Consuelo Hot Springs", "Fossil Site"],
    economy: "Agriculture, forestry, mining, ecotourism",
    languages: ["Cebuano", "Butuanon", "Tagalog"]
  },
  "Aklan": {
    status: "partial",
    price: 300,
    athletes: [],
    population: "615,475",
    capital: "Kalibo",
    region: "Western Visayas (Region VI)",
    area: "1,760.30 km²",
    density: "350 per km²",
    cities: 0,
    municipalities: 17,
    barangays: 327,
    description: "Famous for the world-renowned Ati-Atihan Festival and as the gateway to Boracay Island.",
    attractions: ["Boracay Island", "Ati-Atihan Festival", "Bakhawan Eco-Park", "Jawili Beach"],
    economy: "Tourism, agriculture, fishing, handicrafts",
    languages: ["Aklanon", "Hiligaynon", "Tagalog"]
  },
  "Albay": {
    status: "partial",
    price: 350,
    athletes: [],
    population: "1,374,768",
    capital: "Legazpi",
    region: "Bicol Region (Region V)",
    area: "2,574.91 km²",
    density: "534 per km²",
    cities: 3,
    municipalities: 15,
    barangays: 720,
    description: "Home to the perfect cone-shaped Mayon Volcano, one of the Philippines' most active volcanoes.",
    attractions: ["Mayon Volcano", "Cagsawa Ruins", "Donsol Whale Shark Watching", "Legazpi Boulevard"],
    economy: "Agriculture, tourism, geothermal energy, abaca production",
    languages: ["Bicolano", "Tagalog"]
  },
  "Antique": {
    status: "available",
    price: 220,
    athletes: [],
    population: "612,974",
    capital: "San Jose de Buenavista",
    region: "Western Visayas (Region VI)",
    area: "2,730.67 km²",
    density: "224 per km²",
    cities: 0,
    municipalities: 18,
    barangays: 590,
    description: "Known for its pristine beaches, mountain ranges, and rich cultural heritage of the Panay Bukidnon people.",
    attractions: ["Seco Island", "Malumpati Cold Spring", "Tibiao Fish Spa", "Mount Nangtud"],
    economy: "Agriculture, fishing, tourism, handicrafts",
    languages: ["Kinaray-a", "Hiligaynon", "Tagalog"]
  },
  "Apayao": {
    status: "available",
    price: 180,
    athletes: [],
    population: "124,366",
    capital: "Kabugao",
    region: "Cordillera Administrative Region (CAR)",
    area: "4,502.33 km²",
    density: "28 per km²",
    cities: 0,
    municipalities: 7,
    barangays: 133,
    description: "The least populated province in the Cordillera region, known for its pristine forests and indigenous culture.",
    attractions: ["Apayao River", "Lussok Cave", "Mount Alang", "Traditional Villages"],
    economy: "Agriculture, forestry, small-scale mining",
    languages: ["Isnag", "Ilocano", "Tagalog"]
  },
  "Aurora": {
    status: "available",
    price: 240,
    athletes: [],
    population: "235,750",
    capital: "Baler",
    region: "Central Luzon (Region III)",
    area: "3,133.40 km²",
    density: "75 per km²",
    cities: 0,
    municipalities: 8,
    barangays: 151,
    description: "Famous for its surfing spots and as the birthplace of President Manuel L. Quezon.",
    attractions: ["Baler Bay", "Sabang Beach", "Quezon Memorial", "Ditumabo Falls"],
    economy: "Tourism, agriculture, fishing, forestry",
    languages: ["Tagalog", "Ilocano"]
  },
  "Basilan": {
    status: "available",
    price: 200,
    athletes: [],
    population: "426,207",
    capital: "Isabela City",
    region: "Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)",
    area: "3,453.42 km²",
    density: "123 per km²",
    cities: 1,
    municipalities: 11,
    barangays: 210,
    description: "Known for its rubber plantations and diverse cultural heritage with Christian and Muslim communities.",
    attractions: ["Malamawi Island", "Basilan Strait", "Rubber Plantations", "Cultural Sites"],
    economy: "Rubber production, agriculture, fishing",
    languages: ["Chavacano", "Yakan", "Tausug", "Tagalog"]
  },
  "Bataan": {
    status: "sold",
    price: 400,
    athletes: [],
    population: "853,373",
    capital: "Balanga",
    region: "Central Luzon (Region III)",
    area: "1,372.98 km²",
    density: "622 per km²",
    cities: 1,
    municipalities: 11,
    barangays: 237,
    description: "Historic province known for the Bataan Death March during World War II and Mount Samat National Shrine.",
    attractions: ["Mount Samat National Shrine", "Las Casas Filipinas de Acuzar", "Bataan Nuclear Power Plant", "Dambana ng Kagitingan"],
    economy: "Manufacturing, petrochemicals, tourism, agriculture",
    languages: ["Tagalog", "Kapampangan"]
  },
  "Batanes": {
    status: "premium",
    price: 500,
    athletes: [],
    population: "18,831",
    capital: "Basco",
    region: "Cagayan Valley (Region II)",
    area: "203.22 km²",
    density: "93 per km²",
    cities: 0,
    municipalities: 6,
    barangays: 29,
    description: "The northernmost and smallest province, known for its rolling hills, stone houses, and Ivatan culture.",
    attractions: ["Basco Lighthouse", "Sabtang Island", "Marlboro Hills", "Traditional Stone Houses"],
    economy: "Tourism, agriculture, fishing, livestock",
    languages: ["Ivatan", "Ilocano", "Tagalog"]
  },
  "Batangas": {
    status: "sold",
    price: 450,
    athletes: [],
    population: "2,908,494",
    capital: "Batangas City",
    region: "CALABARZON (Region IV‑A)",
    area: "3,115.05 km²",
    density: "934 per km²",
    cities: 4,
    municipalities: 30,
    barangays: 1078,
    description: "Known for its beaches, diving spots, and as the coffee capital of the Philippines.",
    attractions: ["Taal Volcano", "Anilao Diving Sites", "Nasugbu Beaches", "Basilica of St. Martin de Tours"],
    economy: "Manufacturing, tourism, agriculture, coffee production",
    languages: ["Tagalog", "Batangueño"]
  },
  "Benguet": {
    status: "partial",
    price: 280,
    athletes: [],
    population: "460,683",
    capital: "La Trinidad",
    region: "Cordillera Administrative Region (CAR)",
    area: "2,769.08 km²",
    density: "166 per km²",
    cities: 0,
    municipalities: 13,
    barangays: 140,
    description: "Known as the Salad Bowl of the Philippines for its vegetable production and cool climate.",
    attractions: ["Baguio City", "Strawberry Fields", "Mount Pulag", "Atok Flower Gardens"],
    economy: "Agriculture, mining, tourism, flower cultivation",
    languages: ["Ibaloi", "Kankanaey", "Tagalog"]
  },
  "Biliran": {
    status: "available",
    price: 200,
    athletes: [],
    population: "179,312",
    capital: "Naval",
    region: "Eastern Visayas (Region VIII)",
    area: "536.01 km²",
    density: "335 per km²",
    cities: 0,
    municipalities: 8,
    barangays: 132,
    description: "An island province known for its waterfalls, hot springs, and pristine beaches.",
    attractions: ["Sambawan Island", "Ulan-Ulan Falls", "Mainit Hot Spring", "Agta Beach"],
    economy: "Agriculture, fishing, tourism, geothermal energy",
    languages: ["Waray", "Cebuano", "Tagalog"]
  },
  "Bohol": {
    status: "sold",
    price: 400,
    athletes: [],
    population: "1,394,329",
    capital: "Tagbilaran",
    region: "Central Visayas (Region VII)",
    area: "4,772.52 km²",
    density: "292 per km²",
    cities: 1,
    municipalities: 47,
    barangays: 1109,
    description: "Famous for the Chocolate Hills, tarsiers, and beautiful beaches of Panglao Island.",
    attractions: ["Chocolate Hills", "Tarsier Sanctuary", "Panglao Island", "Loboc River"],
    economy: "Tourism, agriculture, fishing, handicrafts",
    languages: ["Boholano", "Cebuano", "Tagalog"]
  },
  "Bukidnon": {
    status: "partial",
    price: 300,
    athletes: [],
    population: "1,541,308",
    capital: "Malaybalay",
    region: "Northern Mindanao (Region X)",
    area: "10,498.59 km²",
    density: "147 per km²",
    cities: 2,
    municipalities: 20,
    barangays: 464,
    description: "Known as the Food Basket of Mindanao, famous for pineapple and banana plantations.",
    attractions: ["Mount Kitanglad", "Dahilayan Adventure Park", "Del Monte Plantation", "Monastery of Transfiguration"],
    economy: "Agriculture, pineapple production, livestock, tourism",
    languages: ["Cebuano", "Bukidnon", "Tagalog"]
  },
  "Bulacan": {
    status: "sold",
    price: 450,
    athletes: [],
    population: "3,708,890",
    capital: "Malolos",
    region: "Central Luzon (Region III)",
    area: "2,783.69 km²",
    density: "1,332 per km²",
    cities: 3,
    municipalities: 21,
    barangays: 569,
    description: "Known as the Cradle of Heroes and the Republic, birthplace of many Filipino heroes and the First Philippine Republic.",
    attractions: ["Barasoain Church", "Malolos Cathedral", "Angat Dam", "Biak-na-Bato National Park"],
    economy: "Manufacturing, agriculture, aquaculture, tourism",
    languages: ["Tagalog", "Kapampangan"]
  },
  "Cagayan": {
    status: "partial",
    price: 320,
    athletes: [],
    population: "1,268,603",
    capital: "Tuguegarao",
    region: "Cagayan Valley (Region II)",
    area: "9,398.07 km²",
    density: "135 per km²",
    cities: 1,
    municipalities: 28,
    barangays: 820,
    description: "Known for its tobacco production and the Cagayan River, the longest river in the Philippines.",
    attractions: ["Callao Cave", "Cagayan River", "Palaui Island", "Anguib Beach"],
    economy: "Agriculture, tobacco production, fishing, tourism",
    languages: ["Ilocano", "Itawis", "Tagalog"]
  },
  "Camarines Norte": {
    status: "available",
    price: 240,
    athletes: [],
    population: "629,699",
    capital: "Daet",
    region: "Bicol Region (Region V)",
    area: "2,277.93 km²",
    density: "276 per km²",
    cities: 0,
    municipalities: 12,
    barangays: 282,
    description: "Known for its gold mining industry and beautiful beaches along the Pacific coast.",
    attractions: ["Bagasbas Beach", "Calaguas Islands", "Paracale Gold Mines", "Vinzons Shrine"],
    economy: "Mining, agriculture, fishing, tourism",
    languages: ["Bicolano", "Tagalog"]
  },
  "Camarines Sur": {
    status: "partial",
    price: 350,
    athletes: [],
    population: "2,068,244",
    capital: "Pili",
    region: "Bicol Region (Region V)",
    area: "5,511.90 km²",
    density: "375 per km²",
    cities: 2,
    municipalities: 35,
    barangays: 1063,
    description: "Home to the Bicol Express dish and known for wakeboarding at CamSur Watersports Complex.",
    attractions: ["CamSur Watersports Complex", "Mount Isarog", "Caramoan Islands", "Our Lady of Peñafrancia"],
    economy: "Agriculture, aquaculture, tourism, manufacturing",
    languages: ["Bicolano", "Tagalog"]
  },
  "Camiguin": {
    status: "premium",
    price: 400,
    athletes: [],
    population: "92,808",
    capital: "Mambajao",
    region: "Northern Mindanao (Region X)",
    area: "241.44 km²",
    density: "384 per km²",
    cities: 0,
    municipalities: 5,
    barangays: 58,
    description: "Known as the Island Born of Fire, famous for its seven volcanoes and hot springs.",
    attractions: ["White Island", "Sunken Cemetery", "Ardent Hot Springs", "Hibok-Hibok Volcano"],
    economy: "Tourism, agriculture, fishing, handicrafts",
    languages: ["Cebuano", "Hiligaynon", "Tagalog"]
  },
  "Capiz": {
    status: "available",
    price: 260,
    athletes: [],
    population: "804,952",
    capital: "Roxas",
    region: "Western Visayas (Region VI)",
    area: "2,594.64 km²",
    density: "310 per km²",
    cities: 1,
    municipalities: 16,
    barangays: 473,
    description: "Known as the Seafood Capital of the Philippines, famous for its fresh seafood and aswang folklore.",
    attractions: ["Roxas City Seafood Market", "Panay Church", "Suhot Cave", "Baybay Beach"],
    economy: "Fishing, aquaculture, agriculture, tourism",
    languages: ["Capiznon", "Hiligaynon", "Tagalog"]
  },
  "Catanduanes": {
    status: "available",
    price: 220,
    athletes: [],
    population: "271,879",
    capital: "Virac",
    region: "Bicol Region (Region V)",
    area: "1,492.16 km²",
    density: "182 per km²",
    cities: 0,
    municipalities: 11,
    barangays: 315,
    description: "Known as the Land of the Howling Winds, famous for its surfing spots and pristine beaches.",
    attractions: ["Puraran Beach", "Maribina Falls", "Twin Rock Beach Resort", "Luyang Cave"],
    economy: "Agriculture, fishing, tourism, abaca production",
    languages: ["Bicolano", "Tagalog"]
  },
  "Cavite": {
    status: "sold",
    price: 500,
    athletes: [],
    population: "4,344,829",
    capital: "Trece Martires",
    region: "CALABARZON (Region IV‑A)",
    area: "1,526.28 km²",
    density: "2,847 per km²",
    cities: 7,
    municipalities: 16,
    barangays: 829,
    description: "Known as the Historical Capital of the Philippines, birthplace of Philippine independence.",
    attractions: ["Aguinaldo Shrine", "Corregidor Island", "Tagaytay Ridge", "People's Park in the Sky"],
    economy: "Manufacturing, agriculture, tourism, real estate",
    languages: ["Tagalog", "Chavacano"]
  },
  "Cebu": {
    status: "premium",
    price: 600,
    athletes: [
      {
        id: 2,
        name: "Juan Dela Cruz",
        age: 28,
        province: "Cebu",
        profilePic: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
        achievements: ["Cebu Marathon Champion 2023", "Regional 10K Record Holder"],
        personalRecords: {
          "5K": "15:30",
          "10K": "32:15",
          "Half Marathon": "1:10:45",
          "Marathon": "2:25:30"
        },
        bio: "Professional runner from Cebu City, specializing in long-distance events.",
        socialMedia: {
          facebook: "juan.delacruz.runner",
          instagram: "@juanruns",
          strava: "juan-dela-cruz"
        }
      }
    ],
    population: "3,325,385",
    capital: "Cebu City",
    region: "Central Visayas (Region VII)",
    area: "4,943.72 km²",
    density: "673 per km²",
    cities: 6,
    municipalities: 44,
    barangays: 1066,
    description: "The Queen City of the South, known for its rich history, vibrant culture, and as a major economic hub in the Visayas.",
    attractions: ["Magellan's Cross", "Basilica del Santo Niño", "Temple of Leah", "Sirao Flower Garden"],
    economy: "Manufacturing, tourism, IT-BPO, shipping, real estate",
    languages: ["Cebuano", "Tagalog", "English"]
  },
  "Cotabato": {
    status: "available",
    price: 280,
    athletes: [],
    population: "1,490,618",
    capital: "Kidapawan",
    region: "SOCCSKSARGEN (Region XII)",
    area: "9,317.30 km²",
    density: "160 per km²",
    cities: 1,
    municipalities: 17,
    barangays: 543,
    description: "Known for Mount Apo, the highest peak in the Philippines, and diverse agricultural products.",
    attractions: ["Mount Apo", "Lake Venado", "Asik-Asik Falls", "Kidapawan Nature Park"],
    economy: "Agriculture, livestock, mining, tourism",
    languages: ["Hiligaynon", "Cebuano", "Maguindanaon", "Tagalog"]
  },
  "Davao Occidental": {
    status: "available",
    price: 240,
    athletes: [],
    population: "317,159",
    capital: "Malita",
    region: "Davao Region (Region XI)",
    area: "2,163.45 km²",
    density: "147 per km²",
    cities: 0,
    municipalities: 5,
    barangays: 105,
    description: "The newest province in the Philippines, known for its pristine beaches and marine sanctuaries.",
    attractions: ["Sarangani Bay", "Balut Island", "Don Marcelino Beach", "Marine Sanctuaries"],
    economy: "Fishing, agriculture, tourism, coconut production",
    languages: ["Cebuano", "Chavacano", "Tagalog"]
  },
  "Davao Oriental": {
    status: "available",
    price: 260,
    athletes: [],
    population: "576,343",
    capital: "Mati",
    region: "Davao Region (Region XI)",
    area: "5,679.64 km²",
    density: "101 per km²",
    cities: 1,
    municipalities: 10,
    barangays: 183,
    description: "Known for its beautiful coastline, surfing spots, and the sleeping dinosaur formation.",
    attractions: ["Sleeping Dinosaur", "Dahican Beach", "Pujada Bay", "Mount Hamiguitan"],
    economy: "Agriculture, fishing, tourism, coconut production",
    languages: ["Cebuano", "Mandaya", "Tagalog"]
  },
  "Davao de Oro": {
    status: "partial",
    price: 300,
    athletes: [],
    population: "767,547",
    capital: "Nabunturan",
    region: "Davao Region (Region XI)",
    area: "4,560.09 km²",
    density: "168 per km²",
    cities: 0,
    municipalities: 11,
    barangays: 237,
    description: "Formerly Compostela Valley, known for its gold mining industry and banana plantations.",
    attractions: ["Mount Diwata", "Mainit Hot Springs", "New Bataan Falls", "Gold Mining Sites"],
    economy: "Mining, agriculture, banana production, tourism",
    languages: ["Cebuano", "Mansaka", "Tagalog"]
  },
  "Davao del Norte": {
    status: "partial",
    price: 350,
    athletes: [],
    population: "1,125,057",
    capital: "Tagum",
    region: "Davao Region (Region XI)",
    area: "3,422.61 km²",
    density: "329 per km²",
    cities: 3,
    municipalities: 8,
    barangays: 223,
    description: "Known for its banana plantations and as the gateway to Samal Island.",
    attractions: ["Samal Island", "Banana Beach", "Tagum City", "Energy Park"],
    economy: "Agriculture, banana production, tourism, manufacturing",
    languages: ["Cebuano", "Tagalog"]
  },
  "Davao del Sur": {
    status: "premium",
    price: 400,
    athletes: [
      {
        id: 3,
        name: "Ana Reyes",
        age: 24,
        province: "Davao del Sur",
        profilePic: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
        achievements: ["Davao Marathon Winner 2023", "National Youth Champion"],
        personalRecords: {
          "5K": "17:45",
          "10K": "36:20",
          "Half Marathon": "1:18:30",
          "Marathon": "2:45:15"
        },
        bio: "Rising star in Philippine running, representing Davao del Sur in national competitions.",
        socialMedia: {
          facebook: "ana.reyes.runner",
          instagram: "@anaruns",
          strava: "ana-reyes"
        }
      }
    ],
    population: "680,481",
    capital: "Digos",
    region: "Davao Region (Region XI)",
    area: "2,163.98 km²",
    density: "314 per km²",
    cities: 1,
    municipalities: 9,
    barangays: 232,
    description: "Home to Davao City, the largest city in the Philippines by land area, known for durian and safety.",
    attractions: ["Philippine Eagle Center", "Eden Nature Park", "Crocodile Park", "Durian Plantations"],
    economy: "Agriculture, tourism, manufacturing, durian production",
    languages: ["Cebuano", "Tagalog"]
  },
  "Dinagat Islands": {
    status: "available",
    price: 200,
    athletes: [],
    population: "128,117",
    capital: "San Jose",
    region: "Caraga (Region XIII)",
    area: "817.47 km²",
    density: "157 per km²",
    cities: 0,
    municipalities: 7,
    barangays: 100,
    description: "An island province known for its pristine beaches, diving spots, and rich marine biodiversity.",
    attractions: ["Lake Bababu", "Bitaug Beach", "Blue Cathedral", "Diving Sites"],
    economy: "Mining, fishing, agriculture, tourism",
    languages: ["Surigaonon", "Cebuano", "Tagalog"]
  },
  "Eastern Samar": {
    status: "available",
    price: 220,
    athletes: [],
    population: "477,168",
    capital: "Borongan",
    region: "Eastern Visayas (Region VIII)",
    area: "4,617.16 km²",
    density: "103 per km²",
    cities: 1,
    municipalities: 22,
    barangays: 597,
    description: "Known for its rugged coastline, surfing spots, and the Sohoton Natural Bridge National Park.",
    attractions: ["Sohoton Natural Bridge", "Homonhon Island", "Calicoan Island", "Surfing Spots"],
    economy: "Agriculture, fishing, tourism, coconut production",
    languages: ["Waray", "Tagalog"]
  },
  "Guimaras": {
    status: "available",
    price: 220,
    athletes: [],
    population: "187,842",
    capital: "Jordan",
    region: "Western Visayas (Region VI)",
    area: "611.87 km²",
    density: "307 per km²",
    cities: 0,
    municipalities: 5,
    barangays: 98,
    description: "Known as the Mango Capital of the Philippines, famous for its sweet mangoes.",
    attractions: ["Guisi Beach", "Trappist Monastery", "Mango Plantations", "Alubihod Beach"],
    economy: "Agriculture, mango production, tourism, fishing",
    languages: ["Hiligaynon", "Tagalog"]
  },
  "Ifugao": {
    status: "premium",
    price: 450,
    athletes: [],
    population: "207,498",
    capital: "Lagawe",
    region: "Cordillera Administrative Region (CAR)",
    area: "2,618.01 km²",
    density: "79 per km²",
    cities: 0,
    municipalities: 11,
    barangays: 176,
    description: "Home to the UNESCO World Heritage Banaue Rice Terraces, known as the Eighth Wonder of the World.",
    attractions: ["Banaue Rice Terraces", "Batad Rice Terraces", "Tappiya Falls", "Hungduan Rice Terraces"],
    economy: "Agriculture, tourism, handicrafts, rice production",
    languages: ["Ifugao", "Ilocano", "Tagalog"]
  },
  "Ilocos Norte": {
    status: "partial",
    price: 320,
    athletes: [],
    population: "609,588",
    capital: "Laoag",
    region: "Ilocos Region (Region I)",
    area: "3,418.75 km²",
    density: "178 per km²",
    cities: 2,
    municipalities: 21,
    barangays: 559,
    description: "Known for its Spanish colonial architecture, windmills, and as the birthplace of Ferdinand Marcos.",
    attractions: ["Bangui Windmills", "Paoay Church", "Sand Dunes", "Cape Bojeador Lighthouse"],
    economy: "Agriculture, tourism, wind energy, garlic production",
    languages: ["Ilocano", "Tagalog"]
  },
  "Ilocos Sur": {
    status: "partial",
    price: 300,
    athletes: [],
    population: "706,009",
    capital: "Vigan",
    region: "Ilocos Region (Region I)",
    area: "2,596.00 km²",
    density: "272 per km²",
    cities: 2,
    municipalities: 32,
    barangays: 768,
    description: "Home to the UNESCO World Heritage City of Vigan, known for its preserved Spanish colonial architecture.",
    attractions: ["Vigan Heritage Village", "Calle Crisologo", "Bantay Bell Tower", "Hidden Garden"],
    economy: "Tourism, agriculture, handicrafts, tobacco production",
    languages: ["Ilocano", "Tagalog"]
  },
  "Iloilo": {
    status: "sold",
    price: 400,
    athletes: [],
    population: "2,051,899",
    capital: "Iloilo City",
    region: "Western Visayas (Region VI)",
    area: "4,997.64 km²",
    density: "411 per km²",
    cities: 1,
    municipalities: 42,
    barangays: 1721,
    description: "Known as the Heart of the Philippines, famous for its festivals, cuisine, and historic churches.",
    attractions: ["Miagao Church", "Dinagyang Festival", "Guimaras Strait", "Jaro Cathedral"],
    economy: "Agriculture, aquaculture, tourism, manufacturing",
    languages: ["Hiligaynon", "Tagalog"]
  },
  "Isabela": {
    status: "partial",
    price: 350,
    athletes: [],
    population: "1,697,050",
    capital: "Ilagan",
    region: "Cagayan Valley (Region II)",
    area: "13,102.05 km²",
    density: "130 per km²",
    cities: 3,
    municipalities: 34,
    barangays: 1055,
    description: "The largest province in the Philippines by land area, known as the Rice Granary of the North.",
    attractions: ["Magat Dam", "Fuyot Springs National Park", "Ilagan Sanctuary", "Bambanti Festival"],
    economy: "Agriculture, rice production, corn production, livestock",
    languages: ["Ilocano", "Gaddang", "Tagalog"]
  },
  "Kalinga": {
    status: "available",
    price: 200,
    athletes: [],
    population: "229,570",
    capital: "Tabuk",
    region: "Cordillera Administrative Region (CAR)",
    area: "3,282.04 km²",
    density: "70 per km²",
    cities: 1,
    municipalities: 7,
    barangays: 153,
    description: "Known for its rich indigenous culture, traditional tattoos, and the Chico River.",
    attractions: ["Chico River", "Traditional Villages", "Rice Terraces", "Cultural Sites"],
    economy: "Agriculture, mining, handicrafts, tourism",
    languages: ["Kalinga", "Ilocano", "Tagalog"]
  },
  "La Union": {
    status: "partial",
    price: 350,
    athletes: [],
    population: "822,352",
    capital: "San Fernando",
    region: "Ilocos Region (Region I)",
    area: "1,499.28 km²",
    density: "548 per km²",
    cities: 1,
    municipalities: 19,
    barangays: 576,
    description: "Known as the Surfing Capital of the North, famous for its beaches and surf breaks.",
    attractions: ["San Juan Surf Spots", "Poro Point", "Ma-Cho Temple", "Thunderbird Resort"],
    economy: "Tourism, agriculture, fishing, surfing industry",
    languages: ["Ilocano", "Pangasinan", "Tagalog"]
  },
  "Laguna": {
    status: "sold",
    price: 500,
    athletes: [],
    population: "3,382,193",
    capital: "Santa Cruz",
    region: "CALABARZON (Region IV‑A)",
    area: "1,928.23 km²",
    density: "1,754 per km²",
    cities: 6,
    municipalities: 24,
    barangays: 681,
    description: "Known for its hot springs, historical sites, and as the birthplace of José Rizal.",
    attractions: ["Rizal Shrine", "Pagsanjan Falls", "Los Baños Hot Springs", "Enchanted Kingdom"],
    economy: "Manufacturing, agriculture, tourism, education",
    languages: ["Tagalog"]
  },
  "Lanao del Norte": {
    status: "available",
    price: 260,
    athletes: [],
    population: "722,902",
    capital: "Tubod",
    region: "Northern Mindanao (Region X)",
    area: "3,354.16 km²",
    density: "216 per km²",
    cities: 0,
    municipalities: 22,
    barangays: 462,
    description: "Known for its diverse culture, beautiful landscapes, and Lake Lanao.",
    attractions: ["Lake Lanao", "Tinago Falls", "Maria Cristina Falls", "Cultural Sites"],
    economy: "Agriculture, fishing, hydroelectric power, tourism",
    languages: ["Maranao", "Cebuano", "Tagalog"]
  },
  "Lanao del Sur": {
    status: "available",
    price: 240,
    athletes: [],
    population: "1,195,518",
    capital: "Marawi",
    region: "Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)",
    area: "15,055.51 km²",
    density: "79 per km²",
    cities: 1,
    municipalities: 39,
    barangays: 1159,
    description: "The largest province by land area, known for Lake Lanao and Maranao culture.",
    attractions: ["Lake Lanao", "Grand Mosque", "Torogan Houses", "Maranao Cultural Sites"],
    economy: "Agriculture, fishing, handicrafts, livestock",
    languages: ["Maranao", "Tagalog"]
  },
  "Leyte": {
    status: "partial",
    price: 300,
    athletes: [],
    population: "1,776,847",
    capital: "Tacloban",
    region: "Eastern Visayas (Region VIII)",
    area: "6,335.44 km²",
    density: "280 per km²",
    cities: 2,
    municipalities: 40,
    barangays: 1503,
    description: "Historic province where General MacArthur landed during World War II, known for its resilience.",
    attractions: ["MacArthur Landing Memorial", "San Juanico Bridge", "Lake Danao", "Kalanggaman Island"],
    economy: "Agriculture, fishing, geothermal energy, tourism",
    languages: ["Waray", "Cebuano", "Tagalog"]
  },
  "Maguindanao": {
    status: "available",
    price: 220,
    athletes: [],
    population: "1,342,179",
    capital: "Shariff Aguak",
    region: "Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)",
    area: "9,968.31 km²",
    density: "135 per km²",
    cities: 0,
    municipalities: 36,
    barangays: 508,
    description: "Known for its rich Islamic culture, traditional crafts, and the Maguindanao people.",
    attractions: ["Sultan Kudarat Monument", "Traditional Mosques", "Cultural Sites", "Pulangi River"],
    economy: "Agriculture, fishing, handicrafts, livestock",
    languages: ["Maguindanaon", "Tagalog"]
  },
  "Marinduque": {
    status: "available",
    price: 240,
    athletes: [],
    population: "239,207",
    capital: "Boac",
    region: "MIMAROPA Region",
    area: "952.58 km²",
    density: "251 per km²",
    cities: 0,
    municipalities: 6,
    barangays: 218,
    description: "Known as the Heart of the Philippines due to its shape, famous for the Moriones Festival.",
    attractions: ["Moriones Festival", "Tres Reyes Islands", "Poctoy White Beach", "Boac Cathedral"],
    economy: "Agriculture, mining, fishing, tourism",
    languages: ["Tagalog"]
  },
  "Masbate": {
    status: "available",
    price: 260,
    athletes: [],
    population: "908,920",
    capital: "Masbate City",
    region: "Bicol Region (Region V)",
    area: "4,138.56 km²",
    density: "220 per km²",
    cities: 1,
    municipalities: 20,
    barangays: 550,
    description: "Known as the Cattle Country of the Philippines, famous for its rodeo festivals.",
    attractions: ["Rodeo Masbateño", "Buntod Sandbar", "Animasola Island", "Cattle Ranches"],
    economy: "Livestock, agriculture, mining, fishing",
    languages: ["Masbateño", "Bicolano", "Tagalog"]
  },
  "Metro Manila": {
    status: "premium",
    price: 800,
    athletes: [
      {
        id: 1,
        name: "Maria Santos",
        age: 26,
        province: "Metro Manila",
        profilePic: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
        achievements: ["Manila Marathon Champion 2023", "SEA Games Qualifier"],
        personalRecords: {
          "5K": "16:45",
          "10K": "34:20",
          "Half Marathon": "1:15:30",
          "Marathon": "2:35:45"
        },
        bio: "Elite runner from Manila, representing the Philippines in international competitions.",
        socialMedia: {
          facebook: "maria.santos.runner",
          instagram: "@mariasantos",
          strava: "maria-santos"
        }
      }
    ],
    population: "13,484,462",
    capital: "Manila",
    region: "National Capital Region (NCR)",
    area: "619.57 km²",
    density: "21,765 per km²",
    cities: 16,
    municipalities: 1,
    barangays: 1710,
    description: "The National Capital Region, political, economic, and cultural center of the Philippines.",
    attractions: ["Rizal Park", "Intramuros", "Manila Bay", "National Museum", "Binondo Chinatown"],
    economy: "Finance, commerce, manufacturing, tourism, government",
    languages: ["Filipino", "English", "Tagalog"]
  },
  "Misamis Occidental": {
    status: "available",
    price: 260,
    athletes: [],
    population: "617,333",
    capital: "Oroquieta",
    region: "Northern Mindanao (Region X)",
    area: "2,006.63 km²",
    density: "308 per km²",
    cities: 3,
    municipalities: 14,
    barangays: 490,
    description: "Known for its beautiful beaches, diving spots, and the Hoyohoy Highland Adventure.",
    attractions: ["Hoyohoy Highland", "Misamis Occidental Aquamarine Park", "Diving Sites", "Beaches"],
    economy: "Agriculture, fishing, tourism, coconut production",
    languages: ["Cebuano", "Subanon", "Tagalog"]
  },
  "Misamis Oriental": {
    status: "partial",
    price: 300,
    athletes: [],
    population: "956,900",
    capital: "Cagayan de Oro",
    region: "Northern Mindanao (Region X)",
    area: "3,131.52 km²",
    density: "306 per km²",
    cities: 2,
    municipalities: 23,
    barangays: 424,
    description: "Home to Cagayan de Oro, known for white water rafting and as the Gateway to Northern Mindanao.",
    attractions: ["White Water Rafting", "Macahambus Adventure Park", "Divine Mercy Hills", "Gardens of Malasag"],
    economy: "Agriculture, manufacturing, tourism, commerce",
    languages: ["Cebuano", "Tagalog"]
  },
  "Mountain Province": {
    status: "available",
    price: 220,
    athletes: [],
    population: "158,200",
    capital: "Bontoc",
    region: "Cordillera Administrative Region (CAR)",
    area: "2,389.43 km²",
    density: "66 per km²",
    cities: 0,
    municipalities: 10,
    barangays: 144,
    description: "Known for its hanging coffins, rice terraces, and rich indigenous culture.",
    attractions: ["Hanging Coffins of Sagada", "Sumaguing Cave", "Rice Terraces", "Mount Data"],
    economy: "Agriculture, tourism, handicrafts, mining",
    languages: ["Bontoc", "Kankanaey", "Ilocano", "Tagalog"]
  },
  "Negros Occidental": {
    status: "sold",
    price: 450,
    athletes: [],
    population: "2,623,172",
    capital: "Bacolod",
    region: "Western Visayas (Region VI)",
    area: "7,844.12 km²",
    density: "334 per km²",
    cities: 12,
    municipalities: 19,
    barangays: 601,
    description: "Known as the Sugar Bowl of the Philippines, famous for the MassKara Festival.",
    attractions: ["MassKara Festival", "The Ruins", "Mambukal Resort", "Sugar Plantations"],
    economy: "Sugar production, agriculture, tourism, manufacturing",
    languages: ["Hiligaynon", "Tagalog"]
  },
  "Negros Oriental": {
    status: "partial",
    price: 350,
    athletes: [],
    population: "1,432,990",
    capital: "Dumaguete",
    region: "Central Visayas (Region VII)",
    area: "5,420.57 km²",
    density: "264 per km²",
    cities: 6,
    municipalities: 19,
    barangays: 557,
    description: "Known for its universities, diving spots, and the gentle people of Dumaguete.",
    attractions: ["Apo Island", "Twin Lakes", "Casaroro Falls", "Silliman University"],
    economy: "Education, tourism, agriculture, fishing",
    languages: ["Cebuano", "Tagalog"]
  },
  "Northern Samar": {
    status: "available",
    price: 220,
    athletes: [],
    population: "639,186",
    capital: "Catarman",
    region: "Eastern Visayas (Region VIII)",
    area: "3,694.96 km²",
    density: "173 per km²",
    cities: 0,
    municipalities: 24,
    barangays: 569,
    description: "Known for its pristine beaches, caves, and the Biri Rock Formations.",
    attractions: ["Biri Rock Formations", "Capul Island", "San Bernardino Strait", "Caves"],
    economy: "Agriculture, fishing, tourism, coconut production",
    languages: ["Waray", "Tagalog"]
  },
  "Nueva Ecija": {
    status: "partial",
    price: 350,
    athletes: [],
    population: "2,310,134",
    capital: "Palayan",
    region: "Central Luzon (Region III)",
    area: "5,689.69 km²",
    density: "406 per km²",
    cities: 5,
    municipalities: 27,
    barangays: 849,
    description: "Known as the Rice Granary of the Philippines, major rice-producing province.",
    attractions: ["Minalungao National Park", "Nueva Ecija University of Science and Technology", "Rice Fields"],
    economy: "Agriculture, rice production, livestock, aquaculture",
    languages: ["Tagalog", "Ilocano"]
  },
  "Nueva Vizcaya": {
    status: "available",
    price: 240,
    athletes: [],
    population: "497,432",
    capital: "Bayombong",
    region: "Cagayan Valley (Region II)",
    area: "4,813.88 km²",
    density: "103 per km²",
    cities: 0,
    municipalities: 15,
    barangays: 275,
    description: "Known for its citrus fruits and as a gateway to the Cordillera region.",
    attractions: ["Salinas Salt Spring", "Imugan Falls", "Citrus Plantations", "Mount Palali"],
    economy: "Agriculture, citrus production, livestock, forestry",
    languages: ["Ilocano", "Gaddang", "Tagalog"]
  },
  "Occidental Mindoro": {
    status: "available",
    price: 240,
    athletes: [],
    population: "525,354",
    capital: "Mamburao",
    region: "MIMAROPA Region",
    area: "5,851.09 km²",
    density: "90 per km²",
    cities: 0,
    municipalities: 11,
    barangays: 222,
    description: "Known for its pristine beaches, diving spots, and the Apo Reef Natural Park.",
    attractions: ["Apo Reef Natural Park", "White Beach", "Mount Iglit-Baco National Park", "Diving Sites"],
    economy: "Agriculture, fishing, tourism, mining",
    languages: ["Tagalog", "Mangyan languages"]
  },
  "Oriental Mindoro": {
    status: "available",
    price: 260,
    athletes: [],
    population: "908,339",
    capital: "Calapan",
    region: "MIMAROPA Region",
    area: "4,364.74 km²",
    density: "208 per km²",
    cities: 1,
    municipalities: 14,
    barangays: 426,
    description: "Known for its beautiful beaches, the Tamaraw (dwarf buffalo), and Puerto Galera.",
    attractions: ["Puerto Galera", "Tamaraw Conservation Program", "White Beach", "Diving Sites"],
    economy: "Tourism, agriculture, fishing, livestock",
    languages: ["Tagalog", "Mangyan languages"]
  },
  "Palawan": {
    status: "premium",
    price: 600,
    athletes: [],
    population: "939,594",
    capital: "Puerto Princesa",
    region: "MIMAROPA Region",
    area: "14,649.73 km²",
    density: "64 per km²",
    cities: 1,
    municipalities: 22,
    barangays: 433,
    description: "Known as the Last Frontier, famous for the Underground River and pristine islands.",
    attractions: ["Puerto Princesa Underground River", "El Nido", "Coron", "Tubbataha Reefs"],
    economy: "Tourism, fishing, agriculture, mining",
    languages: ["Tagalog", "Cuyonon", "Palawano"]
  },
  "Pampanga": {
    status: "sold",
    price: 450,
    athletes: [],
    population: "2,609,744",
    capital: "San Fernando",
    region: "Central Luzon (Region III)",
    area: "2,180.68 km²",
    density: "1,197 per km²",
    cities: 2,
    municipalities: 19,
    barangays: 538,
    description: "Known as the Culinary Capital of the Philippines, famous for its cuisine and festivals.",
    attractions: ["Mount Pinatubo", "Clark Freeport Zone", "San Guillermo Church", "Culinary Tours"],
    economy: "Manufacturing, tourism, agriculture, aviation",
    languages: ["Kapampangan", "Tagalog"]
  },
  "Pangasinan": {
    status: "partial",
    price: 380,
    athletes: [],
    population: "3,163,190",
    capital: "Lingayen",
    region: "Ilocos Region (Region I)",
    area: "5,451.01 km²",
    density: "580 per km²",
    cities: 4,
    municipalities: 44,
    barangays: 1364,
    description: "Known for the Hundred Islands National Park and as a major salt and fish producer.",
    attractions: ["Hundred Islands", "Bolinao Falls", "Cape Bolinao Lighthouse", "Lingayen Beach"],
    economy: "Agriculture, fishing, salt production, tourism",
    languages: ["Pangasinan", "Ilocano", "Tagalog"]
  },
  "Quezon": {
    status: "partial",
    price: 350,
    athletes: [],
    population: "1,950,459",
    capital: "Lucena",
    region: "CALABARZON (Region IV‑A)",
    area: "8,989.39 km²",
    density: "217 per km²",
    cities: 2,
    municipalities: 39,
    barangays: 1242,
    description: "The largest province in Luzon, known for its coconut production and beautiful islands.",
    attractions: ["Pahiyas Festival", "Villa Escudero", "Kamay ni Hesus", "Borawan Island"],
    economy: "Agriculture, coconut production, fishing, tourism",
    languages: ["Tagalog"]
  },
  "Quirino": {
    status: "available",
    price: 200,
    athletes: [],
    population: "203,828",
    capital: "Cabarroguis",
    region: "Cagayan Valley (Region II)",
    area: "3,057.73 km²",
    density: "67 per km²",
    cities: 0,
    municipalities: 6,
    barangays: 132,
    description: "The second youngest province, known for its forest reserves and the Siitan River.",
    attractions: ["Siitan River", "Governor Rapids", "Forest Reserves", "Aglipay Caves"],
    economy: "Agriculture, forestry, livestock, fishing",
    languages: ["Ilocano", "Ifugao", "Tagalog"]
  },
  "Rizal": {
    status: "sold",
    price: 450,
    athletes: [],
    population: "3,330,143",
    capital: "Antipolo",
    region: "CALABARZON (Region IV‑A)",
    area: "1,182.65 km²",
    density: "2,816 per km²",
    cities: 1,
    municipalities: 13,
    barangays: 188,
    description: "Named after the national hero José Rizal, known for its proximity to Metro Manila.",
    attractions: ["Antipolo Cathedral", "Hinulugang Taktak", "Daranak Falls", "Art in Island"],
    economy: "Manufacturing, agriculture, tourism, real estate",
    languages: ["Tagalog"]
  },
  "Romblon": {
    status: "available",
    price: 220,
    athletes: [],
    population: "308,985",
    capital: "Romblon",
    region: "MIMAROPA Region",
    area: "1,533.45 km²",
    density: "201 per km²",
    cities: 0,
    municipalities: 17,
    barangays: 259,
    description: "Known as the Marble Capital of the Philippines, famous for its marble products.",
    attractions: ["Marble Quarries", "Bonbon Beach", "Tiamban Beach", "Fort San Andres"],
    economy: "Marble quarrying, agriculture, fishing, tourism",
    languages: ["Romblomanon", "Tagalog"]
  },
  "Samar": {
    status: "available",
    price: 240,
    athletes: [],
    population: "780,481",
    capital: "Catbalogan",
    region: "Eastern Visayas (Region VIII)",
    area: "6,048.03 km²",
    density: "129 per km²",
    cities: 1,
    municipalities: 26,
    barangays: 951,
    description: "Known for its caves, waterfalls, and the Sohoton Natural Bridge National Park.",
    attractions: ["Sohoton Natural Bridge", "Langun-Gobingob Cave", "Bangon Falls", "Ulot River"],
    economy: "Agriculture, fishing, forestry, tourism",
    languages: ["Waray", "Tagalog"]
  },
  "Sarangani": {
    status: "available",
    price: 220,
    athletes: [],
    population: "651,319",
    capital: "Alabel",
    region: "SOCCSKSARGEN (Region XII)",
    area: "2,980.01 km²",
    density: "219 per km²",
    cities: 0,
    municipalities: 7,
    barangays: 230,
    description: "Known for its tuna industry and beautiful beaches along Sarangani Bay.",
    attractions: ["Sarangani Bay", "Tuna Fishing", "Gumasa Beach", "Bird Watching"],
    economy: "Fishing, tuna industry, agriculture, tourism",
    languages: ["Cebuano", "Blaan", "Tagalog"]
  },
  "Siquijor": {
    status: "premium",
    price: 400,
    athletes: [],
    population: "103,395",
    capital: "Siquijor",
    region: "Central Visayas (Region VII)",
    area: "337.49 km²",
    density: "306 per km²",
    cities: 0,
    municipalities: 6,
    barangays: 126,
    description: "Known as the Island of Fire, famous for its mystical reputation and beautiful beaches.",
    attractions: ["Cambugahay Falls", "Salagdoong Beach", "Old Enchanted Balete Tree", "Lazi Church"],
    economy: "Tourism, agriculture, fishing, handicrafts",
    languages: ["Cebuano", "Tagalog"]
  },
  "Sorsogon": {
    status: "available",
    price: 260,
    athletes: [],
    population: "740,743",
    capital: "Sorsogon City",
    region: "Bicol Region (Region V)",
    area: "2,119.01 km²",
    density: "349 per km²",
    cities: 1,
    municipalities: 14,
    barangays: 541,
    description: "Known for whale shark watching in Donsol and as the southernmost province of Luzon.",
    attractions: ["Donsol Whale Shark Watching", "Bulusan Volcano", "Paguriran Island", "Barcelona Church"],
    economy: "Tourism, agriculture, fishing, abaca production",
    languages: ["Bicolano", "Waray", "Tagalog"]
  },
  "South Cotabato": {
    status: "available",
    price: 280,
    athletes: [],
    population: "1,408,862",
    capital: "Koronadal",
    region: "SOCCSKSARGEN (Region XII)",
    area: "3,935.95 km²",
    density: "358 per km²",
    cities: 1,
    municipalities: 10,
    barangays: 199,
    description: "Known for its pineapple plantations and the T'nalak Festival celebrating T'boli culture.",
    attractions: ["Lake Sebu", "T'nalak Festival", "Pineapple Plantations", "Seven Falls"],
    economy: "Agriculture, pineapple production, livestock, tourism",
    languages: ["Hiligaynon", "Cebuano", "T'boli", "Tagalog"]
  },
  "Southern Leyte": {
    status: "available",
    price: 220,
    athletes: [],
    population: "421,750",
    capital: "Maasin",
    region: "Eastern Visayas (Region VIII)",
    area: "1,734.85 km²",
    density: "243 per km²",
    cities: 1,
    municipalities: 18,
    barangays: 500,
    description: "Known for its whale watching, diving spots, and the Agas-Agas Bridge.",
    attractions: ["Whale Watching", "Agas-Agas Bridge", "Limasawa Island", "Diving Sites"],
    economy: "Agriculture, fishing, tourism, coconut production",
    languages: ["Cebuano", "Waray", "Tagalog"]
  },
  "Sultan Kudarat": {
    status: "available",
    price: 240,
    athletes: [],
    population: "675,644",
    capital: "Isulan",
    region: "SOCCSKSARGEN (Region XII)",
    area: "5,298.34 km²",
    density: "128 per km²",
    cities: 1,
    municipalities: 11,
    barangays: 249,
    description: "Known for its agricultural products and diverse cultural heritage.",
    attractions: ["Cultural Sites", "Agricultural Tours", "Traditional Villages", "Natural Springs"],
    economy: "Agriculture, livestock, fishing, rice production",
    languages: ["Hiligaynon", "Maguindanaon", "Cebuano", "Tagalog"]
  },
  "Sulu": {
    status: "available",
    price: 200,
    athletes: [],
    population: "851,669",
    capital: "Jolo",
    region: "Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)",
    area: "2,688.18 km²",
    density: "317 per km²",
    cities: 0,
    municipalities: 19,
    barangays: 410,
    description: "An island province known for its rich Islamic culture and pearl diving industry.",
    attractions: ["Pearl Farms", "Traditional Mosques", "Cultural Sites", "Marine Sanctuaries"],
    economy: "Pearl diving, fishing, agriculture, seaweed farming",
    languages: ["Tausug", "Tagalog"]
  },
  "Surigao del Norte": {
    status: "available",
    price: 260,
    athletes: [],
    population: "534,636",
    capital: "Surigao City",
    region: "Caraga (Region XIII)",
    area: "2,739.01 km²",
    density: "195 per km²",
    cities: 1,
    municipalities: 20,
    barangays: 335,
    description: "Known for its surfing spots, particularly Cloud 9 in Siargao Island.",
    attractions: ["Siargao Island", "Cloud 9 Surfing", "Sohoton Cove", "Magpupungko Rock Pools"],
    economy: "Tourism, surfing industry, fishing, agriculture",
    languages: ["Surigaonon", "Cebuano", "Tagalog"]
  },
  "Surigao del Sur": {
    status: "available",
    price: 240,
    athletes: [],
    population: "642,255",
    capital: "Tandag",
    region: "Caraga (Region XIII)",
    area: "4,932.80 km²",
    density: "130 per km²",
    cities: 1,
    municipalities: 16,
    barangays: 309,
    description: "Known for its pristine beaches, waterfalls, and the Enchanted River.",
    attractions: ["Enchanted River", "Tinuy-an Falls", "Britania Islands", "Hinatuan River"],
    economy: "Tourism, agriculture, fishing, mining",
    languages: ["Surigaonon", "Cebuano", "Tagalog"]
  },
  "Tarlac": {
    status: "partial",
    price: 320,
    athletes: [],
    population: "1,503,456",
    capital: "Tarlac City",
    region: "Central Luzon (Region III)",
    area: "3,053.45 km²",
    density: "492 per km²",
    cities: 1,
    municipalities: 17,
    barangays: 511,
    description: "Known for its sugar production and as the birthplace of Presidents Aquino.",
    attractions: ["Aquino Center and Museum", "Mount Telakawa", "Monasterio de Tarlac", "Sugar Plantations"],
    economy: "Agriculture, sugar production, rice production, livestock",
    languages: ["Kapampangan", "Pangasinan", "Ilocano", "Tagalog"]
  },
  "Tawi-Tawi": {
    status: "available",
    price: 200,
    athletes: [],
    population: "440,465",
    capital: "Bongao",
    region: "Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)",
    area: "1,087.40 km²",
    density: "405 per km²",
    cities: 0,
    municipalities: 11,
    barangays: 313,
    description: "The southernmost province, known for its pristine islands and rich marine biodiversity.",
    attractions: ["Turtle Islands", "Bongao Peak", "Marine Sanctuaries", "Cultural Sites"],
    economy: "Fishing, seaweed farming, agriculture, tourism",
    languages: ["Tausug", "Sama", "Tagalog"]
  },
  "Zambales": {
    status: "partial",
    price: 320,
    athletes: [],
    population: "649,615",
    capital: "Iba",
    region: "Central Luzon (Region III)",
    area: "3,830.83 km²",
    density: "170 per km²",
    cities: 1,
    municipalities: 13,
    barangays: 247,
    description: "Known for its beaches, surfing spots, and the former Clark Air Base.",
    attractions: ["Subic Bay", "Crystal Beach", "Anawangin Cove", "Capones Island"],
    economy: "Tourism, fishing, agriculture, manufacturing",
    languages: ["Zambal", "Tagalog", "Ilocano"]
  },
  "Zamboanga del Norte": {
    status: "available",
    price: 260,
    athletes: [],
    population: "1,047,455",
    capital: "Dipolog",
    region: "Zamboanga Peninsula (Region IX)",
    area: "7,301.00 km²",
    density: "143 per km²",
    cities: 2,
    municipalities: 25,
    barangays: 691,
    description: "Known for its sardine industry and beautiful beaches along the Sulu Sea.",
    attractions: ["Dakak Beach Resort", "Rizal Shrine", "Dipolog Boulevard", "Sardine Industry"],
    economy: "Fishing, sardine canning, agriculture, tourism",
    languages: ["Cebuano", "Subanon", "Tagalog"]
  },
  "Zamboanga del Sur": {
    status: "available",
    price: 280,
    athletes: [],
    population: "1,050,668",
    capital: "Pagadian",
    region: "Zamboanga Peninsula (Region IX)",
    area: "4,499.46 km²",
    density: "233 per km²",
    cities: 1,
    municipalities: 26,
    barangays: 681,
    description: "Known for its tri-city (Pagadian) and diverse agricultural products.",
    attractions: ["Pagadian City", "Dao-Dao Islands", "Agricultural Tours", "Cultural Sites"],
    economy: "Agriculture, fishing, coconut production, livestock",
    languages: ["Cebuano", "Subanon", "Tagalog"]
  },
  "Zamboanga Sibugay": {
    status: "available",
    price: 240,
    athletes: [],
    population: "634,244",
    capital: "Ipil",
    region: "Zamboanga Peninsula (Region IX)",
    area: "3,087.59 km²",
    density: "205 per km²",
    cities: 0,
    municipalities: 16,
    barangays: 389,
    description: "Known for its pearl farms and beautiful coastal areas.",
    attractions: ["Pearl Farms", "Coastal Areas", "Traditional Villages", "Marine Sanctuaries"],
    economy: "Pearl farming, fishing, agriculture, coconut production",
    languages: ["Cebuano", "Subanon", "Tagalog"]
  }
};

export default provinceData;

